# Generated by Django 5.1.15 on 2026-02-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aioutput",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_outputs",
                to="tracker.application",
            ),
        ),
    ]
