# Generated by Django 5.1.15 on 2026-02-23 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0002_initial"),
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aioutput",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_outputs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="cvdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cv_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_descriptions",
                to="tracker.application",
            ),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_descriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aioutput",
            name="job_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_outputs",
                to="ai.jobdescription",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_answers",
                to="ai.interviewquestion",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_597c4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cvdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="unique_user_primary_cv",
            ),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(
                fields=["content_hash"], name="job_descrip_content_ad15ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobdescription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash__isnull", False)),
                fields=("user", "content_hash"),
                name="unique_user_content_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="aioutput",
            index=models.Index(
                fields=["user", "type"], name="ai_outputs_user_id_5a56f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aioutput",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_outputs_user_id_7c6ba5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("question__isnull", False),
                    ("custom_question__isnull", False),
                    _connector="OR",
                ),
                name="question_or_custom_question",
            ),
        ),
    ]
