# Generated by Django 5.1.15 on 2026-02-23 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("date_applied", models.DateTimeField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Under Review", "Under Review"),
                            ("Phone Screen", "Phone Screen"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("job_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("salary_min", models.IntegerField(blank=True, null=True)),
                ("salary_max", models.IntegerField(blank=True, null=True)),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_needs_review", models.BooleanField(default=False)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "parse_metadata",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "raw_email_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-date_applied"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applied", "Applied"),
                            ("Under Review", "Under Review"),
                            ("Phone Screen", "Phone Screen"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Under Review", "Under Review"),
                            ("Phone Screen", "Phone Screen"),
                            ("Interview", "Interview"),
                            ("Offer", "Offer"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("email_parser", "Email Parser"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Application status histories",
                "db_table": "application_status_history",
                "ordering": ["changed_at"],
            },
        ),
    ]
